### PR TITLE
Rename England to UK

### LINKED ISSUE #128: England -> UK
> Not a question but a suggestion. I live in England and am very aware that the residents of Scotland and Wales don't like to be classed as "English". You might want to change the title to the more neutral (and correct) Britain, Great Britain, GB, United Kingdom, or UK.

### PR DESCRIPTION
**Pull request by JodiWarren**
Fixes #128

### CODE REVIEW

**Comment by plouc** [comment]
@JodiWarren, Thank you, however it's a temporary fix as the all the data is generated from the cli

**Comment by IeuanG** [comment]
The region in question is actually Great Britain, not the UK. The UK includes Northern Ireland, whereas Great Britain is just England, Wales & Scotland. [Here's a helpful diagram](https://brilliantmaps.com/eng-gb-uk/)

**Comment by RazerM** [comment]
@IeuanG It's definitely the UK.
screenshot 2018-11-19 at 23 02 49

**Comment by IeuanG** [comment]
@RazerM  You're correct, I didn't notice they included NI on that map.

**Comment by plouc** [comment]
Fixed by https://github.com/StateOfJS/StateOfJS/commit/f44145482b61b0da3501c2b0c7b0ad46b96bc3d4

**Pull request closed without merging**
