### PR TITLE
Remove unnecessary word from the conclusion

### PR DESCRIPTION
**Pull request by tienle**
I and many of my friends/colleagues really appreciate your huge effort to bring us invaluable data through this survey. 
However, I would like to suggest a minor amendment to the 2018 conclusion that while still preserving fully the meaning of the message. 
Many thanks,

### CODE REVIEW

**Comment by SachaG** [comment]
Can I ask why you want to remove the word Vietnamese?

**Comment by tienle** [comment]
@SachaG  Well, as a Vietnamese, I'm afraid that it can lead to a different interpretation due the culture. I cannot say for the mass, but I think if this tiny amendment is _likely_ an improvement on the situation then it's worth.

**Comment by SachaG** [comment]
I still don't really understand what the misunderstanding would be so I need to think about it a little more… but if there's anybody else that feels the same way about this issue I'll accept the change :)

**Comment by namvoeh** [comment]
I am curious that why do we need claim exactly the nationality? It is redundant and may be misleading, I agree with the requester we can remove it while the meaning is same.

**Comment by phamtuan2993** [comment]
IMHO, it's okay to me either way, with or without the word, the meaning stay the same

but it's still a valid concern that there would be misunderstanding and this removal is simply a small reasonable enhancement, to me

**Comment by phamtuan2993** [comment]
ah, forgot about other translations as well, in case you would accept this removal, please update them all

**Comment by SachaG** [comment]
I can change it in English but I can't change it in languages I don't speak, sorry… I still don't understand what the misunderstanding would be though. Why is it bad that the person in the hypothetical scenario I created is from Vietnam?

**Pull request merged**
