### PR TITLE
[translation] Russian (ru-RU)

### PR DESCRIPTION
**Pull request by andrey-semin**
### User Interface

- [x] General
- [x] Opinions
- [x] Generic Opinions
- [x] Salary Ranges
- [x] Company Size
- [x] Years of Experience
- [x] Sections
- [x] Tools
- [x] Pages
- [x] Blocks
- [x] Reasons
- [x] Quadrant
- [x] Awards
- [x] Sharing

### Introductions

- [x] Awards
- [x] Back-end Frameworks
- [x] Connections
- [x] Data Layer
- [x] Demographics
- [x] Front-end Frameworks
- [x] Introduction
- [x] Flavors
- [x] Mobile & Desktop
- [x] Opinions
- [x] Other Tools
- [x] Testing

### Conclusions

- [x] Back-end Frameworks
- [x] Conclusion
- [x] Data Layer
- [x] Front-end Frameworks
- [x] Flavors
- [x] Mobile & Desktop
- [x] Testing

### CODE REVIEW

**Comment by vbelolapotkov** [comment]
@andrey-semin hey, I'd like to help with Russian translation as well. Could you please give me write permissions to your fork?

**Comment by vbelolapotkov** [comment]
FYI, I've started translating _introductions_ locally. Will push them once ready and have permissions.

**Comment by andrey-semin** [comment]
@vbelolapotkov Hey there! I've sent you an invite.

**Comment by vbelolapotkov** [comment]
@andrey-semin thanks

**Comment by vbelolapotkov** [comment]
@andrey-semin could you please edit checklist at the top by putting checks in `Introductions` list

**Comment by andrey-semin** [comment]
@vbelolapotkov I'll review your changes once I have some spare time(probably during the next 2-3 days as I'm traveling right now). Thanks for your efforts! I appreciate it! Happy New Year!

**Comment by EdPutans** [comment]
Hey, could you please give me write permissions, I'd like to contribute a bit.
Thanks)

**Comment by andrey-semin** [comment]
@EdPutans Hey there! I've added you as a collaborator, you can push your commits now.

@EdPutans @vbelolapotkov Guys can you please post here what do you plan to work on in order to prevent any collisions?

**Comment by vbelolapotkov** [comment]
I'm working on a ui translation section by section when I have spare time.

**Comment by vbelolapotkov** [comment]
Translated sections, tools and quadrants. Probably will be able to translate awards and sharing tomorrow.

**Comment by andrey-semin** [comment]
@SachaG finally finished! Can you take a look? Sorry it took so long!

**Comment by SachaG** [comment]
Great work, thanks! I'll add it to the site.

**Pull request merged**
