### PR TITLE
[translation] German (de-DE)

### PR DESCRIPTION
**Pull request by r3sMetz**
### User Interface

- [x] General
- [x] Opinions
- [x] Generic Opinions
- [x] Salary Ranges
- [x] Company Size
- [x] Years of Experience
- [x] Sections
- [x] Tools
- [x] Pages
- [x] Blocks
- [x] Reasons
- [x] Quadrant
- [x] Awards
- [x] Sharing

### Introductions

- [x] Awards
- [x] Back-end Frameworks
- [x] Connections
- [x] Data Layer
- [x] Demographics
- [x] Front-end Frameworks
- [x] Introduction
- [x] Flavors
- [x] Mobile & Desktop
- [x] Opinions
- [x] Other Tools
- [x] Testing

### Conclusions

- [x] Back-end Frameworks
- [x] Conclusion
- [x] Data Layer
- [x] Front-end Frameworks
- [x] Flavors
- [x] Mobile & Desktop
- [x] Testing

___

#### Currency
I think we shouldn't change the currency from $ to €, but iam considering at least doing a **l10n**. What do you think?

### CODE REVIEW

**Comment by r3Metz** [comment]
@ndresx , for sure, thanks! invitation is sent.

**Comment by r3sMetz** [comment]
@plouc hello, is there a reason why introductions/support is not on the checklist?

**Comment by SachaG** [comment]
Oh, the support.md page doesn't need to be translated.

**Comment by r3sMetz** [comment]
@plouc @SachaG , i think were ready here.... any next steps for me?

**Comment by SachaG** [comment]
Nice! No, in that case it's up to me to do the merge :) Great work!

**Pull request merged**
