### PR TITLE
[translation] Simplified Chinese 🇨🇳

### PR DESCRIPTION
**Pull request by S1ngS1ng**
## Clarifications
1. Please note that in Chinese, the rule of applying group separator to a number is different from that in English. Normally we group by 4 digits instead of 3. Hence `30k` (30,000) doesn't make that much sense in Chinese, while `3 万` ("万" means 10 thousand) is the way. For questions on Currency Symbol, see below.
2. For `Introductions/testing-introduction`, I decided to leave it untouched. Since it is all about English puns and malapropism, which serves as in-jokes for English speakers. (P.S. I am wondering how it will be translated into other languages though 😂 ) 

### User Interface
- [x] General
- [x] Opinions
- [x] Generic Opinions
- [x] Salary Ranges
- [x] Company Size
- [x] Years of Experience
- [x] Sections
- [x] Tools
- [x] Pages
- [x] Blocks
- [x] Reasons
- [x] Quadrant
- [x] Awards
- [x] Sharing

### Introductions
- [x] Awards
- [x] Back-end Frameworks
- [x] Connections
- [x] Data Layer
- [x] Demographics
- [x] Front-end Frameworks
- [x] Introduction
- [x] Flavors
- [x] Mobile & Desktop
- [x] Opinions
- [x] Other Tools
- [ ] Testing (**NOT TRANSLATED**, see above)

### Conclusions
- [x] Back-end Frameworks
- [x] Conclusion
- [x] Data Layer
- [x] Front-end Frameworks
- [x] Flavors
- [x] Mobile & Desktop
- [x] Testing

## Questions
1. Modify Units
    <details><summary>See #165 </summary>

    As mentioned [here](https://github.com/StateOfJS/StateOfJS/blob/master/docs/internationalization.md#guidelines), we are not supposed to modify the units. Though, could we make some amendment to the order? IMO, in Chinese, `100 美元` (where "美元" means US dollar) is more of a common way as per writing. Meanwhile, I'd like to hear from others' opinion as well.

    </details>

2. Necessary translation of terms
    <details><summary>Resolved</summary>

    As mentioned [here](https://github.com/StateOfJS/StateOfJS/blob/master/docs/internationalization.md#guidelines), we are not supposed to translate Tool names. Though, I've translated Vanilla JS to "原生 JS" (literally "original JS"). IMO, Vanilla JS is more to a meme in the community of English-speaking devs. While in China, I (blindly) assume that not many people understand the meaning of "Vanilla JS". Same as above, I'd like to hear from others' opinion as well.

    </details>

3. Angular vs Angular 2+
    <details><summary>Resolved. I'll make the change for Conclusion and Introduction ONLY</summary>

    As per Angular 2 mentioned [here](https://github.com/StateOfJS/StateOfJS/blob/master/surveys/2018/website/src/translations/en-US.yml#L196), would it be more clear that we say "Angular 2+"? I've made this change as part of PR for translation.

    </details>

4. Tool vs Libraries
    <details><summary>Resolved. We'll use the term tool as long as it applies</summary>

    [Here](https://github.com/StateOfJS/StateOfJS/blob/master/surveys/2018/website/src/translations/en-US.yml#L338-L341) the keys both contain `other_tools`, while the text is `Other Libraries`. Do we need to unify them? I'm translating this text based on "tool" for the reason that "tool" is more generic comparing to "libraries", and it contains "libraries", "framework", "platform", etc.

    </details>

5. Understanding of "over-used"
    <details><summary>Resolved. Translation updated</summary>

    For the word `over-used` mentioned [here](https://github.com/StateOfJS/StateOfJS/blob/master/surveys/2018/website/src/translations/en-US.yml#L509-L510), just wanna double check with you guys. Does this mean that JavaScript is used more frequently or widely than it is expected to be? And for "online", does it mean the development of a website? Or would you mind sharing some examples that JavaScript is over-used? I am not quite sure if I understand this correctly.

    </details>

6. Programming style & patterns intepreted as "Programming Paradigm"?
    <details><summary>Affirmative</summary>

    For the phrase `programming style & patterns` mentioned [here](https://github.com/StateOfJS/StateOfJS/blob/master/surveys/2018/website/src/translations/en-US.yml#L532), I am translating as "Programming Paradigm". Does this introduce any confusion, or is it misinterpreted?

    </details>

7. Understanding of "Robust code"
    <details><summary>Resolved, may be interpreted as "fault tolerance"</summary>

    For the phrase `Robust code` mentioned [here](https://github.com/StateOfJS/StateOfJS/blob/master/surveys/2018/website/src/translations/en-US.yml#L536), as well as `error-prone` and `buggy` later in the file, is it fine if I interpret as "fault tolerance"? IMHO, either the code is `robust` or `buggy` mostly depends on the developers that are using the tool. While "fault tolerance" is more likely to be an intrinsic criterion of a tool.

    </details>

8. Understanding of "well-established option"
    <details><summary>Resolved. Where "option" refers to the tool itself</summary>

    For the phrase `well-established option` mentioned [here](https://github.com/StateOfJS/StateOfJS/blob/master/surveys/2018/website/src/translations/en-US.yml#L547-L550): what exactly is the "option" referring to? If not covered by "package ecosystem" or "developer tooling", I'd consider this to be coding options. But in this case, should it be covered by "Programming Style & patterns"? Or else, does this mean if the tool is versatile (e.g. easy to be combined with other tools thanks to its well-constructed API)?

    </details>

9. Understanding of "New untested option"
    <details><summary>Resolved, as opposite to the above</summary>

    Also, for the `New untested option` mentioned [here](https://github.com/StateOfJS/StateOfJS/blob/master/surveys/2018/website/src/translations/en-US.yml#L600-L601), would you mind elaborating a little bit more on this, please?

    </details>

10. Is Award limited to year 2018 only?
    <details><summary>Resolved. Positive.</summary>

    For the Award, should that be limited to the current year (2018)? I've translated based off the year 2018 in this PR. Instead of: `Awarded to the library with the highest percentage of satisfied users.` I do it this way: `Awarded to the library with the highest percentage of satisfied users in the year 2018.`

    </details>

11. Translation of "State of JS" itself?
    <details><summary>Resolved. We may go ahead and translate it.</summary>

    BTW, I didn't translate "State of JS", unless you guys do need an official name for each language 😂 

    </details>

## Nitpick
1. Missing space between "State" and "of"
    <details><summary>Resolved. PR coming up</summary>

    I think there should be a space between "State" and "of" in [here](https://github.com/StateOfJS/StateOfJS/blob/master/surveys/2018/website/src/translations/en-US.yml#L739). I've made the change in this PR. And if needed, I will submit another PR to fix that in `en-US.yml`.

    </details>

### CODE REVIEW

**Comment by SachaG** [comment]
> As mentioned here, we are not supposed to modify the units. Though, could we make some amendment to the order? IMO, in Chinese, 100 美元 (where "美元" means US dollar) is more of a common way as per writing. Meanwhile, I'd like to hear from others' opinion as well.

I think not modifying units is just a technical limitation. Let's open a new issue thread to discuss the best way to implement that; in the meantime maybe you can add a new `currency` key to the YAML file so that we can use it once the front-end side is ready?

> As mentioned here, we are not supposed to translate Tool names. Though, I've translated Vanilla JS to "原生 JS" (literally "original JS"). IMO, Vanilla JS is more to a meme in the community of English-speaking devs. While in China, I (blindly) assume that not many people understand the meaning of "Vanilla JS". Same as above, I'd like to hear from others' opinion as well.

Yes I think that's the right option, we can translate things when it helps clarify the meaning. 

> As per Angular 2 mentioned here, would it be more clear that we say "Angular 2+"? I've made this change as part of PR for translation.

Maybe but we have to be careful to match the wording used when asking questions if it's in a chart legend or something. On the other hand if it's just in a conclusion or introduction and referring to the actual library rather than the survey results then yes, we can change it. 

> Here the keys both contain other_tools, while the text is Other Libraries. Do we need to unify them? I'm translating this text based on "tool" for the reason that "tool" is more generic comparing to "libraries", and it contains "libraries", "framework", "platform", etc.

This is a debate we had internally, like you guessed we picked "tool" because it's more generic. On the other hand I think in 90% of cases the word "library" is better… But either way we should be consistent so yes, probably use "tool" everywhere. 

> For the word over-used mentioned here, just wanna double check with you guys. Does this mean that JavaScript is used more frequently or widely than it is expected to be? And for "online", does it mean the development of a website? Or would you mind sharing some examples that JavaScript is over-used? I am not quite sure if I understand this correctly.

The intended meaning was "used when it shouldn't be", for example loading a heavy front-end library just to display a static page; loading too many ads; etc. So basically scenarios where JS hurts performance and accessibility and doesn't really benefit the end user. I wanted to reflect that perspective. 

> For the phrase programming style & patterns mentioned here, I am translating as "Programming Paradigm". Does this introduce any confusion, or is it misinterpreted?

I think that's fine. 

> For the phrase Robust code mentioned here, as well as error-prone and buggy later in the file, is it fine if I interpret as "fault tolerance"? IMHO, either the code is robust or buggy mostly depends on the developers that are using the tool. While "fault tolerance" is more likely to be an intrinsic criterion of a tool.

I think that's ok. What I had in mind was languages like TypeScript or even Reason, which use types to make your code (in theory) less buggy. 

> For the phrase well-established option mentioned here: what exactly is the "option" referring to? If not covered by "package ecosystem" or "developer tooling", I'd consider this to be coding options. But in this case, should it be covered by "Programming Style & patterns"? Or else, does this mean if the tool is versatile (e.g. easy to be combined with other tools thanks to its well-constructed API)?

I just meant "well-established library". "option" in this case refers to the tool itself, I just didn't want to keep repeating the words "library", "framework", etc. and also find a word that is applicable to something like e.g. GraphQL, which is not a library or framework.  

> Also, for the New untested option mentioned here, would you mind elaborating a little bit more on this, please?

Just the opposite of the previous one, something that is new and has not been used very widely yet. 

> For the Award, should that be limited to the current year (2018)? I've translated based off the year 2018 in this PR. 

Yes, it's for 2018 only. 

> BTW, I didn't translate "State of JS", unless you guys do need an official name for each language 

I think it's fine to translate it.

> I think there should be a space between "State" and "of" in here. I've made the change in this PR. And if needed, I will submit another PR to fix that in en-US.yml.

Yes, that's a mistake, good catch. 

谢谢你的合作 :)

**Comment by S1ngS1ng** [comment]
@SachaG Thanks for your reply Sacha.
Another quick question if you don't mind:
For Introductions/testing-introduction, I decided to leave it untouched. Since it is all about English puns and malapropism, which serves as in-jokes for English speakers. (P.S. I am wondering how it will be translated into other languages though 😂 )

**Comment by SachaG** [comment]
> For Introductions/testing-introduction, I decided to leave it untouched. Since it is all about English puns and malapropism, which serves as in-jokes for English speakers. 

I think we should translate it, even if we lose the puns… Although yeah without the puns it won't make much sense. Maybe just write your own introduction in Chinese then?

**Comment by SachaG** [comment]
Let me know when this is ready to merge! I would love to have the Chinese version available when we announce the translations "officially" :)

**Comment by S1ngS1ng** [comment]
@SachaG Sorry for the delay. I was tied up with some personal stuff since last month 🤦‍♂️  
I'll be working on this tonight (PST) in ~6 hours.

I agree with your statement:
> Although yeah without the puns it won't make much sense

I would consider it better to create one that is language specific. IMO, more context/explanation needs to be added for non-English speakers in order to explain the puns in English.

Hence for the Testing Introduction page, here is my proposal for the content (posted here in English, will be translated to Chinese upon the update to this PR):
> Nowadays, front end codebase are flooded with more logic than it was before. That's why testing tools are playing a significant role in front end development.

In accordance with other overview pages, I'd rather make that in Testing Introduction straight forward and easy to understand. No puns at this point.

Please let me know your thoughts. Thanks

**Comment by SachaG** [comment]
> Nowadays, front end codebase are flooded with more logic than it was before. That's why testing tools are playing a significant role in front end development.

Looks good to me!

**Comment by S1ngS1ng** [comment]
@SachaG I've made some amendment to it:

In Chinese: 随着客户端的逻辑代码越来越多，测试工具也在前端开发流程中变得越来越重要了。现如今，前端的单元测试和端对端测试工具也日趋完善。

In English (translated directly): As more and more logic code is put in client side, testing tools are becoming more important in front end development. Nowadays, tools of unit test and end-to-end test for front end development is getting mature.

Note that it might seem a little bit weird when translated directly to English. What I may guaranty is that it reads just fine in Chinese 😂

**Comment by S1ngS1ng** [comment]
@SachaG Done. Another question is, does those recently added `yaml` under `typeform/surveys` and `typeform/templates` need to be translated as well?

**Comment by SachaG** [comment]
Great work! 我读中文读得比较漫，但是这个翻译完成了以后，我要看看会不会看得懂;)

> Another question is, does those recently added yaml under typeform/surveys and typeform/templates need to be translated as well?

It would be great to make the survey questions themselves available in other languages for upcoming surveys, but we haven't figured out the right way to do it technically yet (maybe we need to create one Typeform survey per language?). So we can wait a little for that, thanks!

**Comment by S1ngS1ng** [comment]
@SachaG 
> It would be great to make the survey questions themselves available in other languages for upcoming surveys

Agreed 👍 This would definitely increase the number of participants in the future.

> maybe we need to create one Typeform survey per language?

Depending on the survey provider, I believe some platform does support multi-language. Survey Monkey maybe?
Or else, it should be feasible to do the translation based on keywords (i.e. tokens) for options. At some point, translation of a full sentence is required (e.g. the question itself).

Please keep me in the loop, I'd be more than happy to help XD

**Comment by SachaG** [comment]
Yes I think SurveyMonkey supports this, but we've already built a lot of our infrastructure around Typeform… so it'd be tough to switch.

**Pull request merged**
