### PR TITLE
[translation] Hungarian (hu-HU) 🇭🇺

### PR DESCRIPTION
**Pull request by balazsorban44**
### User Interface

- [x] General
- [x] Opinions
- [x] Generic Opinions
- [x] Salary Ranges
- [x] Company Size
- [x] Years of Experience
- [x] Sections
- [x] Tools
- [x] Pages
- [x] Blocks
- [x] Reasons
- [x] Quadrant
- [x] Awards
- [x] Sharing

### Introductions

- [x] Awards
- [x] Back-end Frameworks
- [x] Connections
- [x] Data Layer
- [x] Demographics
- [x] Front-end Frameworks
- [x] Introduction
- [x] Flavors
- [x] Mobile & Desktop
- [x] Opinions
- [x] Other Tools
- [x] Testing

### Conclusions

- [x] Back-end Frameworks
- [x] Conclusion
- [x] Data Layer
- [x] Front-end Frameworks
- [x] Flavors
- [x] Mobile & Desktop
- [x] Testing

### CODE REVIEW

**Comment by balazsorban44** [comment]
🎉 In theory, all the Hungarian 🇭🇺 translations are done :heavy_check_mark:, but we still have to check for typos and double-check if the translations are good enough.

**Comment by SachaG** [comment]
Let me know when this is ready to merge! :)

**Comment by balazsorban44** [comment]
@SachaG it's all yours 😉

**Comment by SachaG** [comment]
Awesome! Here we go!

**Pull request merged**
