### PR TITLE
[translation] French (fr-FR) 🇫🇷

### PR DESCRIPTION
**Pull request by SachaG**
Me and @plouc started on the french translation but despite being french ourselves I think our french is pretty bad… Would love some help ;)

### User Interface

- [x] General
- [x] Opinions
- [x] Generic Opinions
- [x] Salary Ranges
- [x] Company Size
- [x] Years of Experience
- [x] Sections
- [x] Tools
- [x] Pages
- [x] Blocks
- [x] Reasons
- [x] Quadrant
- [x] Awards
- [x] Sharing

### Introductions

- [x] Awards
- [x] Back-end Frameworks
- [x] Connections
- [x] Data Layer
- [x] Demographics
- [x] Front-end Frameworks
- [x] Introduction
- [x] Flavors
- [x] Mobile & Desktop
- [x] Opinions
- [x] Other Tools
- [x] Testing

### Conclusions

- [x] Back-end Frameworks
- [x] Conclusion
- [x] Data Layer
- [x] Front-end Frameworks
- [x] Flavors
- [x] Mobile & Desktop
- [x] Testing

### CODE REVIEW

**Comment by michaelrambeau** [comment]
I translated the conclusion of the Testing section, on the `fr-FR` branch of the repo (not on your fork), check here: https://github.com/StateOfJS/StateOfJS/commit/eeac9ce80924da4fea658b518714d7199c8a2f29

Let me know if it's OK to work on that branch or if you want to work on your fork instead.

**Comment by michaelrambeau** [comment]
OK Sacha, it works, thank you, I have just added a commit to your fork of the repo.

**Comment by sebranly** [comment]
Hey guys, I might be able to help with the French translations (at least, I want to read the final result in order to remove mistakes). I saw that there was a [file](https://gist.github.com/mtancoigne/a2455973c471d1be9bf163b3f58e487c#file-state_of_js_enthusiasts_translators-json-L78) to match people to languages. @mtancoigne please would you mind adding me to the list?

**Comment by SachaG** [comment]
Good idea!

@3dos
@adriantombu
@codeKameleon
@dadeef
@frinyvonnick
@joeltankam
@maevadevs
@mdartic
@mtancoigne
@nrifki
@Nyalab
@Plotisateur
@sarahdayan
@SoulierAntoine

Leave a comment here to let me know if you still have time to help with the translation, and I'll give you access to the repo.

**Comment by mdartic** [comment]
Hello @SachaG, sounds good for me too to check this translation.

**Comment by Nyalab** [comment]
Hello, i'm also available to translate and check transalations already made.

**Comment by Plotisateur** [comment]
I'm a bit late, but still ready to help if any still needed ! :)

**Comment by SachaG** [comment]
@Plotisateur thanks! added you as well

**Comment by mtancoigne** [comment]
I'm a bit late too, and sadly have no more time right now :/

**Comment by Plotisateur** [comment]
I have done some improvements on the spelling, syntax and punctuation ! Might I create a new PR or you reopen this one ?

**Comment by SachaG** [comment]
@Plotisateur you can push your commits directly to https://github.com/SachaG/StateOfJS and then I'll create a PR from there to here. 

Since that's the workflow we use for other languages I want to test it for French, too, to see if it makes sense.

**Pull request merged**
